import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    
    <div className={styles.container}>
      
      {/* <style jsx>
        {`
        h2 {
          font-size: 38px;
        }
        h3 {
          font-size: 28px;
        }
      `}
      </style> */}
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>

      <main className={styles.main}>
    
        <h1 className={styles.title}>
        <span className="dummy">&lt;Hunting Coder/&gt;</span>
        </h1>
        <div className={styles.imageWrap}>
          <img className={styles.myImg} src="/blog1.jfif" alt="Hunting Coder" width={323} height={150}/>
          {/* <Image className={styles.myImg} src='/blog1.jfif' alt='codehunter' width={323} height={150}/> */}
        </div>
        
        
        <div className="blogs">
          <h2>Latest Blogs</h2>
          <div className="blogitems">
            <h3>How to learn Javascript in 2022?</h3>
            <p>Javascript is a language used to design web pages!!</p>
            <button className={styles.button}>Read more</button>
          </div>
          <div className="blogitems">
            <h3>How to learn Javascript in 2022?</h3>
            <p>Javascript is a language used to design web pages!!</p>
            <button className={styles.button}>Read more</button>
          </div>
          <div className="blogitems">
            <h3>How to learn Javascript in 2022?</h3>
            <p>Javascript is a language used to design web pages!!</p>
            <button className={styles.button}>Read more</button>
          </div>
        </div>
  
      </main>

      {/* <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer> */}
    </div>
  )
}
